kind: Secret
apiVersion: v1
metadata:
  name: postgre-secret
  namespace: postgresql
type: Opaque
stringData:
  POSTGRES_DB: customerdb
  POSTGRES_USER: customeruser
  POSTGRES_PASSWORD: khushboo@6391
