CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL
	);


CREATE TABLE IF NOT EXISTS products (
	id SERIAL PRIMARY KEY,
	title VARCHAR(100) NOT NULL,
	price DECIMAL(10,2)
	);


CREATE TABLE IF NOT EXISTS orders(
	id SERIAL PRIMARY KEY,
	user_id INT REFERENCE users(id) ON DELETE CASCADE,
	amount DECIMAL(10,2) NOT NULL,
	status VARCHAR(20) DEFAULT 'pending'
	);



